# Generated by Django 4.2.2 on 2025-12-04 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tapnote", "0003_likerecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="author",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="note",
            name="title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
