# Generated by Django 4.2.2 on 2025-12-04 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tapnote", "0004_note_author_note_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="link_target",
            field=models.CharField(
                choices=[("_blank", "New Tab"), ("_self", "Same Tab")],
                default="_blank",
                max_length=10,
            ),
        ),
    ]
