# Generated by Django 4.2.2 on 2025-12-09 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tapnote", "0007_banneduser"),
    ]

    operations = [
        migrations.CreateModel(
            name="TelegraphAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("short_name", models.CharField(max_length=32)),
                ("author_name", models.CharField(default="Anonymous", max_length=128)),
                ("author_url", models.URLField(blank=True, default="")),
                ("access_token", models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="note",
            name="views",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="note",
            name="account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pages",
                to="tapnote.telegraphaccount",
            ),
        ),
    ]
